# UART Example — LicheeRV Nano

build:
	mkdir -p bin
	${COMPILER}/riscv64-unknown-linux-musl-gcc main.c -o ./bin/uart_test
	@echo "Build complete: bin/uart_test"

clean:
	rm -rf bin

.PHONY: build clean
